name: "Build and Tests"

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    name: "Build and Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        if: success()
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: "Build and Test"
        if: success()
        run: mvn -U -B clean install --file pom.xml
