name: "Package and Delivery"

on:
  push:
    branches: [ "develop" ]

jobs:
  docker:
    name: "Package and Delivery"
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        if: success()
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: "Package with Maven"
        if: success()
        run: mvn -U -B package --file pom.xml

      - name: Increment version
        id: increment-version
        uses: RichardInnocent/semantic-versioning-maven@v0.1.0

      - name: Print if version changed
        if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
        run: echo "The new version is now $new_version"
        env:
          new_version: ${{ steps.increment-version.outputs.new-version }}

      - name: "Docker Setup Buildx"
        if: success()
        uses: docker/setup-buildx-action@v3.0.0
        with:
          platforms: ${{ vars.DOCKER_PLATFORMS }}

      - name: "Docker Login"
        if: success()
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Docker Build and Push"
        if: success()
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: Dockerfile
          platforms: ${{ vars.DOCKER_PLATFORMS }}
          tags: ${{ vars.DOCKERHUB_TAG }}:latest
